### PR TITLE
add build ios framework script

### PR DESCRIPTION
**Pull request by CodeEagle**
add build ios framework script

### CODE REVIEW

**Comment by kewlbear** [comment]
Thanks!

**Comment by SoneeJohn** [comment]
@CodeEagle can you also add a macOS script? I am trying to modify the iOS script to build it into a framework but I am having trouble :-)

**Comment by CodeEagle** [comment]
@SoneeJohn WIP.

**Comment by SoneeJohn** [comment]
@CodeEagle thanks for letting me know :-)

**Pull request merged**
